### ISSUE TITLE
ValueError - Word #-s contains non-alphabetic characters.

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/volpiano-display-utilities#49]
See 500 code at https://staging.cantusdatabase.org/chant/1002695

occurs when manuscript fulltext is `meos me- # me # -s me {#} -s  me- #-s meo-# # -eos meos m-os m-os meo- -eos` and volpiano is `1---g--g---g---g---g---g---g---g---6------6---g---h6------6---h6------6---h6------6---h6------6---6------6--h---6------6--h---6------6--h---6------6--h---`

Traceback from local development environment:

```python
Environment:


Request Method: GET
Request URL: http://localhost:8888/edit-chants/1000016?pk=1002717&folio=001r&ref=chant-list

Django Version: 4.2.11
Python Version: 3.9.19
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.flatpages',
 'django.contrib.humanize',
 'django.contrib.postgres',
 'extra_views',
 'main_app',
 'articles',
 'django_quill',
 'reversion',
 'users',
 'debug_toolbar']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
 'reversion.middleware.RevisionMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/volpiano_display_utilities/text_volpiano_alignment.py", line 337, in align_text_and_volpiano
    syllabified_text = syllabify_text(
  File "/usr/local/lib/python3.9/site-packages/volpiano_display_utilities/cantus_text_syllabification.py", line 185, in syllabify_text
    List[int], syllabify_word(prepared_word, return_string=False)
  File "/usr/local/lib/python3.9/site-packages/volpiano_display_utilities/latin_word_syllabification.py", line 382, in syllabify_word
    raise ValueError(f"Word {word} contains non-alphabetic characters.")

During handling of the above exception (Word #-s contains non-alphabetic characters.), another exception occurred:
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/edit.py", line 204, in get
    return super().get(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/edit.py", line 144, in get
    return self.render_to_response(self.get_context_data())
  File "/code/django/cantusdb_project/main_app/views/chant.py", line 1156, in get_context_data
    text_and_mel, _ = align_text_and_volpiano(
  File "/usr/local/lib/python3.9/site-packages/volpiano_display_utilities/text_volpiano_alignment.py", line 341, in align_text_and_volpiano
    syllabified_text = syllabify_text(
  File "/usr/local/lib/python3.9/site-packages/volpiano_display_utilities/cantus_text_syllabification.py", line 185, in syllabify_text
    List[int], syllabify_word(prepared_word, return_string=False)
  File "/usr/local/lib/python3.9/site-packages/volpiano_display_utilities/latin_word_syllabification.py", line 382, in syllabify_word
    raise ValueError(f"Word {word} contains non-alphabetic characters.")

Exception Type: ValueError at /edit-chants/1000016
Exception Value: Word #-s contains non-alphabetic characters.
```

**Comment by dchiller** [comment]
My current take is that this is in part a CantusDB issue. The view in question should handle this exception and prevent a 500 error from being returned in the case of this type of error. 

With #37, we introduced a paradigm where in cases of a number of different encoding errors, we'd do our best to align the text and volpiano and then return a boolean indicating whether or not some kind of manual correction might actually be warranted. The idea was that we should return something when this is called in a view, but have some sort of mechanism so an alert to the user (a "spell check" of sorts) could be returned at some future point. 

The difference here is that this particular error is coming from the latin syllabification. And my view is: (a) it is much more likely that a bad character in a word is actually an error and not just a misapplication of the encoding rules and (b) unlike alignment errors, where we can make some good guesses with spacing, etc, it is not clear to me what a "best attempt" latin syllabification would with non-latin characters. 

All that being said, I think with the case of "#" not being properly separated from the surrounding words by spaces, we really CAN intuit what is going on, so it is worth finding a way to fit this into the paradigm introduced with #37. 

So, here is what I'm proposing:

- [ ] Handle cases where indexer doesn't surround "#" with spaces a la #37.
- [ ] Introduce a custom exception for this "bad character" case, so that
- [ ] CantusDB views invoking alignment and syllabification can catch that particular exception and handle it in some way.
